<a href="https://colab.research.google.com/github/yejijang-analyst/ESAA_note/blob/main/1_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **[개념정리]**

# **Numpy**

- 루프를 사용하지 않고 대량 데이터의 빠른 배열 연산 속도를 가능하게 하는 패키지  

--------

# **넘파이 ndarray**

- array() 함수의 인자로는 파이썬의 리스트 객체가 주로 사용.
  - 리스트 []는 1차원이고, 리스트의 [[ ]]는 2차원과 같은 형태로 배열의 차원과 크기를 표현
- 연산의 특성상 같은 데이터 타입만 가능(리스트: 서로 다른 데이터 타입 가능)
  - 만약 다른 데이터 유형이 섞여 있는 리스트를 ndarray로 변경하면 데이터 크기가 더 큰 데이터 타입으로 형 변환을 일괄 적용.


---

1) arange()
- range()와 유사한 기능
- 0부터 함수 인자 값 -1까지의 값을 순차적으로 ndarray 데이터 값으로 변환

2) zeros()
- 모든 값은 0으로 채운 해당 shape을 가진 ndarray로 반환


# **[필사]**

In [1]:
import numpy as nps

In [3]:
array1 = np.array([1, 2, 3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)

array2 = np.array([[1,2,3],
                  [4,5,6]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array3 = np.array([[1, 2, 3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)



array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [4]:
print('array1 : {:0}차원, array2 : {:1}차원, array3 : {:2}차원'.format(array1.ndim,array2.ndim,array3.ndim))

array1 : 1차원, array2 : 2차원, array3 :  2차원


In [6]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [7]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [11]:
#astype() 를 통하여 ndarray 내 데이터 값의 타입 변경.

array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1,2.1,3.1])
array_float1 = array_float1.astype('int32')
print(array_float1, array_float1.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


In [13]:
#arange()
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype , sequence_array.shape )

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [21]:
#zeros()
zero_array = np.zeros((3,2), dtype = 'int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

#ones
one_array= np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [ ]:
#reshape()
