<a href="https://colab.research.google.com/github/yejijang-analyst/ESAA_note/blob/main/Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.__version__)
print(np.show_config())

1.23.5
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
array = np.zeros(10)
print(array)



[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [5]:
# 내 풀이 print('array size:', array.size) ## 오답
array4 = np.zeros((10,10))
print("%d bytes" % (array4.size * array4.itemsize))

800 bytes


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
array1 = np.zeros(10)
array1[4] = 1 #4? 5?
print(array1)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
array2 = np.arange(start=10,stop=50)
print(array2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
array2 = np.arange(start=10,stop=50)
array3 = array2[::-1] #np. 붙일 필요 없음
print(array3)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
array33 = np.arange(start=0,stop=9)
array33d = array33.reshape(3,3)
print(array33d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
array9 = np.nonzero([1,2,0,0,4,0])  #####

print(array9)

(array([0, 1, 4]),)


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [ ]:
array_i=np.identity(3)
print(array_i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [ ]:
q11 = np.random.random((3,3,3))
print(q11)

[[[0.91054662 0.87913976 0.75607011]
  [0.68432798 0.24826482 0.49464162]
  [0.37407244 0.38514378 0.24225928]]

 [[0.39750169 0.37784402 0.55926408]
  [0.22250888 0.49623441 0.06173556]
  [0.1161415  0.14654653 0.94559921]]

 [[0.2895782  0.0332383  0.84950713]
  [0.98686448 0.99483615 0.6494694 ]
  [0.53192285 0.50695422 0.94503894]]]


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [ ]:
q11 = np.random.random((10, 10))
print(q11)
print(q11.min(), q11.max()) # 함수 사용시 () 뒤에 괄호 꼭 붙이기

[[0.80651213 0.66287986 0.35940914 0.65777399 0.22532615 0.17222427
  0.73119256 0.54241892 0.59109831 0.09788637]
 [0.70108808 0.14353245 0.54872561 0.2462446  0.51769933 0.56391362
  0.05704498 0.56824207 0.62315259 0.57151593]
 [0.83254837 0.46432535 0.00139336 0.60773741 0.72735827 0.20427311
  0.08128714 0.34751139 0.0427396  0.22031683]
 [0.55558085 0.08382465 0.59793744 0.08868955 0.3346046  0.5647525
  0.16106193 0.79310507 0.18583745 0.88383432]
 [0.72095319 0.35254721 0.08550481 0.57634576 0.34337452 0.6529888
  0.16340107 0.73043687 0.58731236 0.25206798]
 [0.64393494 0.99966935 0.68090098 0.01962915 0.86244961 0.61866005
  0.61466905 0.34498116 0.11153266 0.10525806]
 [0.27893311 0.60911073 0.3699117  0.11183492 0.43185148 0.94882301
  0.50370212 0.58371032 0.26717334 0.44118974]
 [0.21906773 0.88708319 0.01367875 0.66552474 0.55297038 0.88030722
  0.85420818 0.0596087  0.8598609  0.02752391]
 [0.83645055 0.26537856 0.29776075 0.62748203 0.69448654 0.19672093
  0.89332228 0

#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [ ]:
q11 = np.random.random((30))
print(q11)
print('mean:', q11.mean())

[0.37518068 0.6231388  0.64346857 0.14068311 0.49829861 0.30402185
 0.11465569 0.20382151 0.92744702 0.31402118 0.8213977  0.68760971
 0.10772351 0.80597544 0.69315055 0.74740662 0.24087766 0.57622037
 0.02713381 0.68850514 0.19317859 0.0989353  0.18564132 0.88295511
 0.67895556 0.2536385  0.36978176 0.3826691  0.95971227 0.27287601]
mean: 0.46063603472447856


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
x = np.ones((5,5))
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan)  ###
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [ ]:
x = np.diag(1+np.arange(4),k=-1)
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
x = np.zeros((8,8))
print(x)
x[1::2, ::2 ] = 1
x[::2, 1::2 ] = 1
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [ ]:
x = np.unravel_index(100, (6, 7, 8)) #####
print(x)

(1, 5, 4)


#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [ ]:
x = np.random.random((5,5))
print(x)
z = (x - (np.mean(x)))/(np.std(x))
print(z)

y = (x - (x.mean()))/(x.std())
print(y)

[[0.72472426 0.58443599 0.31098351 0.19210487 0.224505  ]
 [0.35017904 0.07023651 0.30616236 0.02617071 0.77509515]
 [0.05207876 0.17860904 0.63442268 0.0477328  0.79265349]
 [0.87097326 0.70241072 0.25887416 0.65653779 0.69137337]
 [0.57963633 0.82000882 0.53567189 0.79773044 0.72205132]]
[[ 0.88916134  0.38721365 -0.59119205 -1.01653666 -0.90060986]
 [-0.45095147 -1.4525784  -0.60844198 -1.61024467  1.06938703]
 [-1.51754635 -1.0648244   0.56606469 -1.53309607  1.13221032]
 [ 1.41243636  0.80932407 -0.7776379   0.64519195  0.76983273]
 [ 0.37004059  1.23008696  0.21273699  1.1503755   0.87959761]]
[[ 0.88916134  0.38721365 -0.59119205 -1.01653666 -0.90060986]
 [-0.45095147 -1.4525784  -0.60844198 -1.61024467  1.06938703]
 [-1.51754635 -1.0648244   0.56606469 -1.53309607  1.13221032]
 [ 1.41243636  0.80932407 -0.7776379   0.64519195  0.76983273]
 [ 0.37004059  1.23008696  0.21273699  1.1503755   0.87959761]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [4]:

color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

my_color = np.array((255, 128, 64, 192), dtype=color)

# 색상 정보 출력
print("빨강:", my_color["r"])
print("초록:", my_color["g"])
print("파랑:", my_color["b"])
print("투명도:", my_color["a"])

# 다른 색상 생성
another_color = np.array((128, 192, 255, 128), dtype=color)

# 색상 정보 출력
print("\n빨강:", another_color["r"])
print("초록:", another_color["g"])
print("파랑:", another_color["b"])
print("투명도:", another_color["a"])

##이렇게 color 데이터 타입을 활용하면 색상 정보를 구조화된 방식으로 저장하고
##다룰 수 있으며, 각 색상 채널에 쉽게 액세스할 수 있습니다.

#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [5]:
array21 = np.dot(np.ones((5,3)), np.ones((3,2)))
print(array21)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [6]:
#"in place"는 새로운 배열을 생성하지 말고 주어진 배열 자체를 수정하라

array22 = np.arange(11)
array22[ ( 3 < array22 ) & ( array22 < 8 )] *= -1 # 인덱싱 기능을 사용
print(array22)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [7]:

print(sum(range(5),-1)) #그냥 sum은 두번째인자를 첫번째 원소로 지정하여 합에 포함
from numpy import *
print(sum(range(5),-1))  #np sum은 두번째 인자의 축을 지정함

9
10


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [34]:
Z = np.array([1, 2, 3, 4, 5], dtype=int)
 # Z**Z
# 2 << Z >> 2
# Z <-  Z

x = 1j * Z
print(x)
y = Z/1/1
y
# v = Z<Z>Z



[0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j]


array([1., 2., 3., 4., 5.])

In [14]:
Z = np.array([1, 2, 3])

# Z를 부호 반전
result1 = -Z

# Z에 1j를 곱함 (복소수로 변환)
result2 = 1j * Z

# Z를 1로 나누고 다시 1로 나눔 (변화 없음)
result3 = Z / 1 / 1

print(result1)  # [-1 -2 -3]
print(result2)  # [0.+1.j 0.+2.j 0.+3.j]
print(result3)  # [1. 2. 3.]







[-1 -2 -3]
[0.+1.j 0.+2.j 0.+3.j]
[1. 2. 3.]


#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [36]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

<ipython-input-36-ee897105b7c6>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
<ipython-input-36-ee897105b7c6>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


array([-9.22337204e+18])

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [43]:

Z1 = np.random.randint(0, 10, 10)
Z2 = np.random.randint(0, 10, 10)

common = np.intersect1d(Z1, Z2) #####np.intersect1d 함수 사용!
print(common)


[0 1 4 5 6 9]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [50]:
print(np.sqrt(-1) == np.emath.sqrt(-1))
print(np.allclose(np.sqrt(-1) , np.emath.sqrt(-1)))

False
False


<ipython-input-50-4ed0071ab13e>:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))
<ipython-input-50-4ed0071ab13e>:2: RuntimeWarning: invalid value encountered in sqrt
  print(np.allclose(np.sqrt(-1) , np.emath.sqrt(-1)))


#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [51]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
Z

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [52]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [57]:
Z = np.random.uniform(0,10,10) #(min,max,size)
print(Z - Z%1) #1로 나눈 나머지를 뺀다. 즉 정수화 ok
print(Z // 1) #1로 나눈 몫을 계산
print(np.floor(Z)) #np.floor 함수는 각 요소를 가장 가까운 작은 정수로 내림
print(Z.astype(int))
print(np.trunc(Z)) # np.trunc 함수는 각 요소를 소수점
#이하를 버리고 가장 가까운 정수로 내립니다.

[4. 7. 5. 9. 0. 4. 3. 3. 6. 5.]
[4. 7. 5. 9. 0. 4. 3. 3. 6. 5.]
[4. 7. 5. 9. 0. 4. 3. 3. 6. 5.]
[4 7 5 9 0 4 3 3 6 5]
[4. 7. 5. 9. 0. 4. 3. 3. 6. 5.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [58]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

#Z += np.arange(5) 코드는 배열 Z의 각 행에 [0, 1, 2, 3, 4]를 더합니다.
#이 연산은 NumPy의 브로드캐스팅(broadcasting)을 활용하여
#각 행에 해당하는 값을 더하는 것을 가능하게 합니다.

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [60]:
z = np.random.random(10)
z.sort()
z

array([0.00296907, 0.09167913, 0.17368971, 0.36982251, 0.45321898,
       0.48019852, 0.58445938, 0.60745865, 0.87153998, 0.92961966])

#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [62]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
np.array_equal(A, B)

False

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [63]:
# 무작위로 생성된 10x2 카테시안 좌표 행렬 생성
cartesian_coordinates = np.random.rand(10, 2)

# 각 점의 x, y 좌표 추출
x = cartesian_coordinates[:, 0]
y = cartesian_coordinates[:, 1]

# 원점으로부터의 거리 계산 (극좌표의 반지름)
radius = np.sqrt(x**2 + y**2)

# x축과 이루는 각도 계산 (극좌표의 각도)
angle = np.arctan2(y, x)

# 결과를 극좌표로 나타낸 행렬 생성
polar_coordinates = np.column_stack((radius, angle))

# 결과 출력
print("카테시안 좌표:")
print(cartesian_coordinates)
print("\n극좌표:")
print(polar_coordinates)



카테시안 좌표:
[[0.39503878 0.73952483]
 [0.82107519 0.53441985]
 [0.59071179 0.9396652 ]
 [0.25259655 0.07996631]
 [0.62347404 0.2167414 ]
 [0.33573707 0.02243041]
 [0.95443156 0.23846968]
 [0.71089574 0.19936662]
 [0.08966807 0.1624731 ]
 [0.61304518 0.05102073]]

극좌표:
[[0.8384227  1.08018068]
 [0.97967803 0.57699225]
 [1.10991491 1.00958327]
 [0.26495212 0.306595  ]
 [0.66007326 0.33456636]
 [0.33648552 0.06671033]
 [0.98377202 0.24484237]
 [0.73832229 0.27342061]
 [0.18557444 1.06649952]
 [0.61516462 0.08303372]]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [64]:
Z = np.random.random(10)
Z[Z.argmax()] = 0 #Z.argmax() 큰값의 인덱스를 찾는다
print(Z)

[0.65078061 0.3167824  0.54502101 0.         0.16406093 0.60719152
 0.19960429 0.67220698 0.3708477  0.42943969]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [65]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

87


#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [66]:

Z = np.arange(9).reshape(3, 3)

for index, value in np.ndenumerate(Z):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [72]:
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((5, 5))

# 임의의 요소 위치를 선택하여 해당 위치에 값을 배치
random_indices = np.random.choice(range(5 * 5), 5, replace=False)
values_to_place = 55  # 원하는 값을 지정

np.put(Z, random_indices, values_to_place)
print(Z)

[[ 0.  0.  0.  0.  0.]
 [55. 55. 55.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [55.  0.  0.  0.  0.]
 [55.  0.  0.  0.  0.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [77]:
# column 1
Z = np.random.randint(0, 10, (3, 3))

# n번째 열을 기준으로 정렬
n = '원하는 열의 인덱스'
sorted_Z = Z[Z[:, 0].argsort()]

print("원본 배열:")
print(Z)

print("\n정렬된 배열:")
print(sorted_Z)

원본 배열:
[[2 5 0]
 [9 5 8]
 [4 9 4]]

정렬된 배열:
[[2 5 0]
 [4 9 4]
 [9 5 8]]


In [78]:
# column 2
Z = np.random.randint(0, 10, (3, 3))

# n번째 열을 기준으로 정렬
n = '원하는 열의 인덱스'
sorted_Z = Z[Z[:, 1].argsort()]

print("원본 배열:")
print(Z)

print("\n정렬된 배열:")
print(sorted_Z)

원본 배열:
[[6 5 2]
 [9 9 4]
 [3 7 1]]

정렬된 배열:
[[6 5 2]
 [3 7 1]
 [9 9 4]]


In [83]:
# column 3
Z = np.random.randint(0, 10, (3, 3))

# n번째 열을 기준으로 정렬
n = '원하는 열의 인덱스'
sorted_Z = Z[Z[:, 2].argsort()] #3이 최대이니까 -1 하여 2 사용
# sorted_Z = Z[:, 2].argsort()
# 해당 Z만뽑혀서 정렬된 배열 모양이 아래처럼 한줄만 뽑혀서 나옴.
#원본에서 바뀐 것을 비교하고 싶으면 위 처럼 짜야함.
# 정렬된 배열:
#[1 0 2]
print("원본 배열:")
print(Z)

print("\n정렬된 배열:")
print(sorted_Z)

원본 배열:
[[6 4 0]
 [8 8 7]
 [1 2 4]]

정렬된 배열:
[[6 4 0]
 [1 2 4]
 [8 8 7]]
