<a href="https://colab.research.google.com/github/yejijang-analyst/ESAA_note/blob/main/Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)
print(np.show_config())

1.23.5
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

#### 3. Create a null vector of size 10 (★☆☆)

In [9]:
array = np.zeros(10)
print(array)



[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [1]:
# 내 풀이 print('array size:', array.size) ## 오답
array4 = np.zeros((10,10))
print("%d bytes" % (array4.size * array4.itemsize)

SyntaxError: ignored

#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [12]:
array1 = np.zeros(10)
array1[4] = 1 #4? 5?
print(array1)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [14]:
array2 = np.arange(start=10,stop=50)
print(array2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [17]:
array2 = np.arange(start=10,stop=50)
array3 = array2[::-1] #np. 붙일 필요 없음
print(array3)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [18]:
array33 = np.arange(start=0,stop=9)
array33d = array33.reshape(3,3)
print(array33d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [45]:
array9 = np.nonzero([1,2,0,0,4,0])  #####

print(array9)

(array([0, 1, 4]),)


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [23]:
array_i=np.identity(3)
print(array_i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [24]:
q11 = np.random.random((3,3,3))
print(q11)

[[[0.91054662 0.87913976 0.75607011]
  [0.68432798 0.24826482 0.49464162]
  [0.37407244 0.38514378 0.24225928]]

 [[0.39750169 0.37784402 0.55926408]
  [0.22250888 0.49623441 0.06173556]
  [0.1161415  0.14654653 0.94559921]]

 [[0.2895782  0.0332383  0.84950713]
  [0.98686448 0.99483615 0.6494694 ]
  [0.53192285 0.50695422 0.94503894]]]


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [31]:
q11 = np.random.random((10, 10))
print(q11)
print(q11.min(), q11.max()) # 함수 사용시 () 뒤에 괄호 꼭 붙이기

[[0.80651213 0.66287986 0.35940914 0.65777399 0.22532615 0.17222427
  0.73119256 0.54241892 0.59109831 0.09788637]
 [0.70108808 0.14353245 0.54872561 0.2462446  0.51769933 0.56391362
  0.05704498 0.56824207 0.62315259 0.57151593]
 [0.83254837 0.46432535 0.00139336 0.60773741 0.72735827 0.20427311
  0.08128714 0.34751139 0.0427396  0.22031683]
 [0.55558085 0.08382465 0.59793744 0.08868955 0.3346046  0.5647525
  0.16106193 0.79310507 0.18583745 0.88383432]
 [0.72095319 0.35254721 0.08550481 0.57634576 0.34337452 0.6529888
  0.16340107 0.73043687 0.58731236 0.25206798]
 [0.64393494 0.99966935 0.68090098 0.01962915 0.86244961 0.61866005
  0.61466905 0.34498116 0.11153266 0.10525806]
 [0.27893311 0.60911073 0.3699117  0.11183492 0.43185148 0.94882301
  0.50370212 0.58371032 0.26717334 0.44118974]
 [0.21906773 0.88708319 0.01367875 0.66552474 0.55297038 0.88030722
  0.85420818 0.0596087  0.8598609  0.02752391]
 [0.83645055 0.26537856 0.29776075 0.62748203 0.69448654 0.19672093
  0.89332228 0

#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [35]:
q11 = np.random.random((30))
print(q11)
print('mean:', q11.mean())

[0.37518068 0.6231388  0.64346857 0.14068311 0.49829861 0.30402185
 0.11465569 0.20382151 0.92744702 0.31402118 0.8213977  0.68760971
 0.10772351 0.80597544 0.69315055 0.74740662 0.24087766 0.57622037
 0.02713381 0.68850514 0.19317859 0.0989353  0.18564132 0.88295511
 0.67895556 0.2536385  0.36978176 0.3826691  0.95971227 0.27287601]
mean: 0.46063603472447856


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [36]:
x = np.ones((5,5))
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [37]:
print(0 * np.nan)  ###
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [40]:
x = np.diag(1+np.arange(4),k=-1)
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [39]:
x = np.zeros((8,8))
print(x)
x[1::2, ::2 ] = 1
x[::2, 1::2 ] = 1
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [47]:
x = np.unravel_index(100, (6, 7, 8)) #####
print(x)

(1, 5, 4)


#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [50]:
x = np.random.random((5,5))
print(x)
z = (x - (np.mean(x)))/(np.std(x))
print(z)

y = (x - (x.mean()))/(x.std())
print(y)

[[0.72472426 0.58443599 0.31098351 0.19210487 0.224505  ]
 [0.35017904 0.07023651 0.30616236 0.02617071 0.77509515]
 [0.05207876 0.17860904 0.63442268 0.0477328  0.79265349]
 [0.87097326 0.70241072 0.25887416 0.65653779 0.69137337]
 [0.57963633 0.82000882 0.53567189 0.79773044 0.72205132]]
[[ 0.88916134  0.38721365 -0.59119205 -1.01653666 -0.90060986]
 [-0.45095147 -1.4525784  -0.60844198 -1.61024467  1.06938703]
 [-1.51754635 -1.0648244   0.56606469 -1.53309607  1.13221032]
 [ 1.41243636  0.80932407 -0.7776379   0.64519195  0.76983273]
 [ 0.37004059  1.23008696  0.21273699  1.1503755   0.87959761]]
[[ 0.88916134  0.38721365 -0.59119205 -1.01653666 -0.90060986]
 [-0.45095147 -1.4525784  -0.60844198 -1.61024467  1.06938703]
 [-1.51754635 -1.0648244   0.56606469 -1.53309607  1.13221032]
 [ 1.41243636  0.80932407 -0.7776379   0.64519195  0.76983273]
 [ 0.37004059  1.23008696  0.21273699  1.1503755   0.87959761]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [ ]:

color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
array21 = np.dot(np.ones((5,3)), np.ones((3,2)))
print(array21)

#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
array22 = np.arange(11)
array22[ ( 3 < array22 ) & ( array22 <= 8 )] *= -1
print(array22)

#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z=[1,2,3]
#Z**Z is not legal
#2 << Z >>2 is no legal
#Z <- Z is not legal
#1j*Z is not legal
#Z/1/1 is not legal
Z<Z>Z


#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0) / np.array(0)   # 결과 : nan
np.array(0) // np.array(0)   # 결과 : 0에 가까운 수
np.array([np.nan]).astype(int).astype(float)

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [ ]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
common=[]
for i in Z1:
    for j in Z2:
        if i==j:
            common.append(j)

print(common)


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
import numpy as np

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 32. Create a random vector of size 10 and sort it (★★☆)

#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [ ]:
# column 1

In [ ]:
# column 2

In [ ]:
# column 3